export enum DataAttrs {
  PRODUCTS_LIST = 'data-products-list',
  PRODUCT_IMG = 'data-product-image',
  PRODUCT_NAME = 'data-product-name',
  PRODUCT_QUANTITY = 'data-product-quantity',
  PRODUCT_CURRENT_PRICE = 'data-product-current-price',
  PRODUCT_OLD_PRICE = 'data-product-old-price',
  PRODUCT_TOTAL_PRICE = 'data-product-total-price',
  PRODUCT_ORIGINAL_TOTAL_PRICE = 'data-product-original-total-price',
  PRODUCT_CARD = 'data-product-card',
  ENTER_EDITING_BUTTON = 'data-enter-editing-button',
  EXIT_EDITING_BUTTON = 'data-exit-editing-button',
  CHANGE_QUANTITY_BUTTON = 'data-change-quantity-button',
  DELETE_BUTTON = 'data-delete-button',
  PROMO_BUTTON = 'data-promo-button',
  PROMO_INPUT = 'data-promo-input',
  PROMO_SUCCESS = 'data-promo-success',
  PROMO_ERROR = 'data-promo-error',
  SHOW_MODAL_BUTTON = 'data-show-modal-button',
  CLEAR_BUTTON = 'data-clear-button',
  CANCEL_BUTTON = 'data-cancel-button',
  ROW = 'data-product-row',
  LABEL = 'data-product-label',
  QUANTITY_INPUT = 'data-quantity-input',
  QUANTITY_BLOCK = 'data-quantity-block',
  QUANTITY_ERROR = 'data-quantity-error',
  DELETE_ERROR = 'data-delete-error',
  TOTAL_PRICE = 'data-total-price',
  ORIGINAL_TOTAL_PRICE = 'data-original-total-price',
  MODAL = 'data-cart-modal',
  MODAL_BODY = 'data-cart-modal-body',
  MODAL_ERROR = 'data-modal-error',
  LINKS_LIST = 'data-links-list',
}

export enum Events {
  CHANGE_TOTAL_PRICE = 'changetotalprice',
  PRODUCT_DELETED = 'productdeleted',
}
